#pragma once

#include "ast/core/ast_node.hpp"
#include "ast/core/basic_list.hpp"
#include "ast/core/binary_operations.hpp"

#include "ast/declarations/class_declaration.hpp"
#include "ast/declarations/class_declaration_list.hpp"
#include "ast/declarations/declaration.hpp"
#include "ast/declarations/declaration_list.hpp"
#include "ast/declarations/field_declaration.hpp"
#include "ast/declarations/method_declaration.hpp"
#include "ast/declarations/variable_declaration.hpp"

#include "ast/expressions/array_idx_expression.hpp"
#include "ast/expressions/bool_expression.hpp"
#include "ast/expressions/compare_op_expression.hpp"
#include "ast/expressions/expression.hpp"
#include "ast/expressions/float_expression.hpp"
#include "ast/expressions/identifier_expression.hpp"
#include "ast/expressions/integer_expression.hpp"
#include "ast/expressions/length_expression.hpp"
#include "ast/expressions/logic_op_expression.hpp"
#include "ast/expressions/math_op_expression.hpp"
#include "ast/expressions/method_call_expression.hpp"
#include "ast/expressions/new_array_expression.hpp"
#include "ast/expressions/new_class_expression.hpp"
#include "ast/expressions/not_expression.hpp"
#include "ast/expressions/this_expression.hpp"

#include "ast/functional/comma_expression_list.hpp"
#include "ast/functional/method_call.hpp"

#include "ast/program/main_class.hpp"
#include "ast/program/program.hpp"


#include "ast/statements/assert_statement.hpp"
#include "ast/statements/assignment_statement.hpp"
#include "ast/statements/if_else_statement.hpp"
#include "ast/statements/if_statement.hpp"
#include "ast/statements/local_variable_statement.hpp"
#include "ast/statements/mehtod_call_statement.hpp"
#include "ast/statements/print_statement.hpp"
#include "ast/statements/return_statement.hpp"
#include "ast/statements/statement_list.hpp"
#include "ast/statements/statement_list_statement.hpp"
#include "ast/statements/statement.hpp"
#include "ast/statements/while_statement.hpp"

#include "ast/values/array_l_value.hpp"
#include "ast/values/field_l_value.hpp"
#include "ast/values/identifier_l_value.hpp"
#include "ast/values/l_value.hpp"